### PR TITLE
fix(streamer): added streamer pagination

### LINKED ISSUE #1010: Add pagination ability on streamer
Given that we can potentially have dozens of thousands of gauges, it's better to have some smart mechanism which spreads block rewards upon multiple blocks to avoid potential dos of chain. 

This should take into account the next epcoh for distribution (so we don't override) and ideally only paginate when a possible performance hit is possible (without forgetting there are other endBlockers which run)

### PR DESCRIPTION
**Pull request by keruch**
## Description

Added streamer pagination. ADR: https://www.notion.so/dymension/ADR-x-Streamer-Pagination-ad21ef72458e472cad9fb6f9932c16cd.

- Added a `BeforeEpochStart` hook
- Modified a `AfterEpochEnd` hook
- Added `EndBlock`
- Now rewards are distributed not in a single block, but along the whole epoch
- Added stream iterator

Please pay special attention to 
- [StreamIterator](https://github.com/dymensionxyz/dymension/blob/kirill/1010-streamer-pagination/x/streamer/keeper/stream_iterator.go)
- [Epoch hooks](https://github.com/dymensionxyz/dymension/blob/kirill/1010-streamer-pagination/x/streamer/keeper/hooks.go)
- [EndBlock](https://github.com/dymensionxyz/dymension/blob/kirill/1010-streamer-pagination/x/streamer/keeper/abci.go)

----

Closes #1010

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [x]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x]  Targeted PR against the correct branch
- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x]  Linked to the GitHub issue with discussion and accepted design
- [x]  Targets only one GitHub issue
- [x]  Wrote unit and integration tests
- [x]  Wrote relevant migration scripts if necessary
- [x]  All CI checks have passed
- [x]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [x]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [x] Registered Invariants
- [x] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map` <- only in one place and under my supervision
- [x] No usage of `time.Now()`
- [x] Used fixed point arithmetic and not float arithmetic
- [x] Avoid panicking in Begin/End block as much as possible
- [x] No unexpected math Overflow
- [x] Used `sendCoin` and not `SendCoins`
- [x] Out-of-block compute is bounded
- [x] No serialized ID at the end of store keys
- [x] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/streamer/keeper/hooks.go [hunk 1]
```diff
@@ -34,54 +36,118 @@ func (k Keeper) Hooks() Hooks {
 /* -------------------------------------------------------------------------- */
 
 // BeforeEpochStart is the epoch start hook.
-func (k Keeper) BeforeEpochStart(ctx sdk.Context, epochIdentifier string, epochNumber int64) error {
+func (k Keeper) BeforeEpochStart(ctx sdk.Context, epochIdentifier string) error {
```
Comment (mtsitrin) [inline x/streamer/keeper/hooks.go:39]: add documantation

File: x/streamer/keeper/hooks.go [hunk 2]
```diff
@@ -34,54 +36,118 @@ func (k Keeper) Hooks() Hooks {
...
 // AfterEpochEnd is the epoch end hook.
-func (k Keeper) AfterEpochEnd(ctx sdk.Context, epochIdentifier string, epochNumber int64) error {
-	streams := k.GetUpcomingStreams(ctx)
-	// move to active if start time reached
-	for _, stream := range streams {
-		if !ctx.BlockTime().Before(stream.StartTime) {
-			if err := k.moveUpcomingStreamToActiveStream(ctx, stream); err != nil {
-				return err
-			}
+func (k Keeper) AfterEpochEnd(ctx sdk.Context, epochIdentifier string) (sdk.Coins, error) {
```
Comment (mtsitrin) [inline x/streamer/keeper/hooks.go:84]: add documantation

File: x/streamer/keeper/distribute.go [hunk 3]
```diff
@@ -3,143 +3,156 @@ package keeper
...
-	remainCoins := stream.Coins.Sub(stream.DistributedCoins...)
-	remainEpochs := stream.NumEpochsPaidOver - stream.FilledEpochs
-
-	for _, coin := range remainCoins {
-		epochAmt := coin.Amount.Quo(sdk.NewInt(int64(remainEpochs)))
-		if epochAmt.IsPositive() {
-			totalDistrCoins = totalDistrCoins.Add(sdk.Coin{Denom: coin.Denom, Amount: epochAmt})
+// UpdateStreamAtEpochStart updates the stream for a new epoch.
+func (k Keeper) UpdateStreamAtEpochStart(ctx sdk.Context, stream types.Stream) (types.Stream, error) {
+	// Check if stream has completed its distribution
```
Comment (mtsitrin) [inline x/streamer/keeper/distribute.go:59]: why u check it on `EpochStart` and not on after the distribution phase?

File: x/streamer/keeper/hooks.go [hunk 4]
```diff
@@ -34,54 +36,118 @@ func (k Keeper) Hooks() Hooks {
...
+	activeStreams := k.GetActiveStreams(ctx)
+
+	var toDistribute []types.Stream
+
+	for _, s := range activeStreams {
+		if epochIdentifier == s.DistrEpochIdentifier {
+			toDistribute = append(toDistribute, s)
 		}
 	}
```
Comment (mtsitrin) [inline x/streamer/keeper/hooks.go:93]: lets wrap it in `k.GetActiveStreamsForEpoch(ctx, epochIdentifier)`, as it's used above as well

File: x/streamer/keeper/keeper.go [hunk 5]
```diff
@@ -81,6 +105,18 @@ func (k Keeper) CreateStream(ctx sdk.Context, coins sdk.Coins, records []types.D
 		return 0, fmt.Errorf("epoch identifier does not exist: %s", epochIdentifier)
 	}
 
+	pointerExists, err := k.HasEpochPointer(ctx, epochIdentifier)
+	if err != nil {
+		return 0, fmt.Errorf("check epoch pointer existence: %w", err)
+	}
+
+	if !pointerExists {
```
Comment (mtsitrin) [inline x/streamer/keeper/keeper.go:113]: can set on genesis with the avaialble `epochs`, as the epoch list is immutable
than u can assume `EpochPointer` exists for all epochs

File: x/streamer/keeper/abci.go [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+	epochPointers, err := k.GetAllEpochPointers(ctx)
+	if err != nil {
+		return fmt.Errorf("get all epoch pointers: %w", err)
+	}
+
+	maxIterations := k.GetParams(ctx).MaxIterationsPerBlock
+	totalIterations := uint64(0)
+	totalDistributed := sdk.NewCoins()
+
+	for _, p := range epochPointers {
```
Comment (mtsitrin) [inline x/streamer/keeper/abci.go:23]: is it sorted? I guess it make more sense to start with the short epochs (e.g min before day)

File: x/streamer/keeper/abci.go [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+
+	// Save stream updates
+	for _, stream := range streams {
+		err = k.SetStream(ctx, &stream)
+		if err != nil {
+			return fmt.Errorf("set stream: %w", err)
+		}
+	}
+
+	err = ctx.EventManager().EmitTypedEvent(&types.EventEndBlock{
```
Comment (zale144) [inline x/streamer/keeper/abci.go:50]:
```suggestion
	err = uevent.EmitTypedEvent(ctx, &types.EventEndBlock{
```

File: x/streamer/keeper/distribute.go [hunk 8]
```diff
@@ -3,143 +3,156 @@ package keeper
...
-	err = k.updateStreamPostDistribute(ctx, stream, totalDistrCoins)
-	if err != nil {
-		return nil, err
+	// Don't fill streams in which there's nothing to fill. Note that rewards are distributed post factum.
+	// I.e., first increase the filled epoch number, then distribute rewards during the epoch.
+	if !stream.DistributeTo.TotalWeight.IsZero() {
+		stream.FilledEpochs += 1
 	}
 
+	// TODO: can we delete this event?
```
Comment (zale144) [inline x/streamer/keeper/distribute.go:95]: if we don't end up deleting it, please use `uevent.EmitTypedEvent` as suggested above

File: x/streamer/keeper/hooks.go [hunk 9]
```diff
@@ -34,54 +36,118 @@ func (k Keeper) Hooks() Hooks {
...
+			return fmt.Errorf("update stream '%d' at epoch start: %w", s.Id, err)
+		}
+		// Save the stream
+		err = k.SetStream(ctx, &updated)
+		if err != nil {
+			return fmt.Errorf("set stream: %w", err)
+		}
+	}
+
+	err := ctx.EventManager().EmitTypedEvent(&types.EventEpochStart{
```
Comment (zale144) [inline x/streamer/keeper/hooks.go:73]: use `uevent.EmitTypedEvent`

File: x/streamer/module.go [hunk 10]
```diff
@@ -155,7 +155,11 @@ func (am AppModule) BeginBlock(_ sdk.Context, _ abci.RequestBeginBlock) {}
 
 // EndBlock executes all ABCI EndBlock logic respective to the module.
 // Returns a nil validatorUpdate struct array.
-func (am AppModule) EndBlock(_ sdk.Context, _ abci.RequestEndBlock) []abci.ValidatorUpdate {
+func (am AppModule) EndBlock(ctx sdk.Context, _ abci.RequestEndBlock) []abci.ValidatorUpdate {
+	err := am.keeper.EndBlock(ctx)
+	if err != nil {
+		panic(err)
```
Comment (zale144) [inline x/streamer/module.go:161]: yeah, do we really need to halt the chain here?

**Review by zale144 — CHANGES_REQUESTED** [review]
nice work. left some comments

**Comment by omritoptix** [comment]
@keruch build fails

File: internal/pagination/paginate.go [hunk 11]
```diff
@@ -0,0 +1,29 @@
+package pagination
```
Comment (zale144) [inline internal/pagination/paginate.go:1]: shouldn't this be somewhere in utils or something?

**Review by zale144 — APPROVED** [review]
very nice

File: x/streamer/keeper/distribute.go [hunk 12]
```diff
@@ -3,143 +3,147 @@ package keeper
...
+	// Add coins to distribute during the next epoch
+	stream.EpochCoins = epochCoins
 
-	err = k.updateStreamPostDistribute(ctx, stream, totalDistrCoins)
-	if err != nil {
-		return nil, err
+	// Don't fill streams in which there's nothing to fill. Note that rewards are distributed post factum.
+	// I.e., first increase the filled epoch number, then distribute rewards during the epoch.
+	if !stream.DistributeTo.TotalWeight.IsZero() {
+		stream.FilledEpochs += 1
```
Comment (mtsitrin) [inline x/streamer/keeper/distribute.go:92]: it's possible for `stream.FilledEpochs = stream.NumEpochsPaidOver`, and thus will be considered `NotActive` for this method:

```
// IsActiveStream returns true if the stream is in an active state during the provided time.
func (stream Stream) IsActiveStream(curTime time.Time) bool {
	if (curTime.After(stream.StartTime) || curTime.Equal(stream.StartTime)) && (stream.FilledEpochs < stream.NumEpochsPaidOver) {
		return true
	}
	return false
}

```
wdyt?

File: x/streamer/keeper/distribute.go [hunk 13]
```diff
@@ -3,143 +3,147 @@ package keeper
...
+
+	// Distribute to all the remaining gauges that are left after EndBlock
+	newPointer, iterations := IterateEpochPointer(pointer, streams, limit, func(v StreamGauge) pagination.Stop {
+		distributed, errX := k.DistributeToGauge(ctx, v.Stream.EpochCoins, v.Gauge, v.Stream.DistributeTo.TotalWeight)
+		if errX != nil {
+			// Ignore this gauge
+			k.Logger(ctx).
+				With("streamID", v.Stream.Id, "gaugeID", v.Gauge.GaugeId, "error", errX.Error()).
+				Error("Failed to distribute to gauge")
 		}
```
Comment (mtsitrin) [inline x/streamer/keeper/distribute.go:126]: need `return pagination.Continue` in case of error?

File: x/streamer/keeper/distribute.go [hunk 14]
```diff
@@ -3,143 +3,147 @@ package keeper
...
+	streams []types.Stream,
+) DistributeRewardsResult {
+	totalDistributed := sdk.NewCoins()
+
+	// Temporary map for convenient calculations
+	streamUpdates := make(map[uint64]sdk.Coins, len(streams))
+
+	// Distribute to all the remaining gauges that are left after EndBlock
+	newPointer, iterations := IterateEpochPointer(pointer, streams, limit, func(v StreamGauge) pagination.Stop {
+		distributed, errX := k.DistributeToGauge(ctx, v.Stream.EpochCoins, v.Gauge, v.Stream.DistributeTo.TotalWeight)
```
Comment (mtsitrin) [inline x/streamer/keeper/distribute.go:120]: don't it need to be in cache ctx?
semi-succefull `DistributeToGauge` should be reverted
otherwise the state can be some undesired state

**Review by mtsitrin — APPROVED** [review]
