### PR TITLE
fix(rollapp): update rollapp fields, add genesis_info

### LINKED ISSUE #1169: Create new genesis sealing level to match IRO, introduce `exponent` and refactor accordingly

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #1169 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/rollapp/types/rollapp.go [hunk 1]
```diff
@@ -88,7 +80,37 @@ func (r Rollapp) ValidateBasic() error {
...
+
+func (r Rollapp) GenesisInfoFieldsAreSet() bool {
+	return r.GenesisInfo.GenesisChecksum != "" &&
+		r.GenesisInfo.NativeDenom != nil &&
+		r.GenesisInfo.NativeDenom.Validate() == nil &&
+		r.GenesisInfo.Bech32Prefix != "" &&
+		!r.GenesisInfo.InitialSupply.IsNil()
+}
+
+func (r GenesisInfo) Validate() error {
```
Comment (omritoptix) [inline x/rollapp/types/rollapp.go:94]: we're missing initial supply validation?

File: x/rollapp/types/rollapp.go [hunk 2]
```diff
@@ -130,6 +152,18 @@ func validateBech32Prefix(prefix string) error {
 	return nil
 }
 
+func (dm DenomMetadata) Validate() error {
+	if dm.Base == "" {
```
Comment (omritoptix) [inline x/rollapp/types/rollapp.go:156]: max len?

File: x/rollapp/types/rollapp.go [hunk 3]
```diff
@@ -130,6 +152,18 @@ func validateBech32Prefix(prefix string) error {
...
+		return errorsmod.Wrap(gerrc.ErrInvalidArgument, "base denom")
+	}
+
+	if dm.Display == "" {
```
Comment (omritoptix) [inline x/rollapp/types/rollapp.go:160]: max len?

File: x/rollapp/types/rollapp.go [hunk 4]
```diff
@@ -130,6 +152,18 @@ func validateBech32Prefix(prefix string) error {
...
+		return errorsmod.Wrap(gerrc.ErrInvalidArgument, "display denom")
+	}
+
+	return nil
+}
+
 func validateMetadata(metadata *RollappMetadata) error {
```
Comment (omritoptix) [inline x/rollapp/types/rollapp.go:167]: metadata validation of fee denom?

**Review by omritoptix — CHANGES_REQUESTED** [review]
seems like in general we're missing validations and updates in relevant places.
we should work more methodically when adding fields and verify all places are updated with validations and checks.

**Review by omritoptix — APPROVED** [review]

File: proto/dymensionxyz/dymension/rollapp/metadata.proto [hunk 5]
```diff
@@ -24,8 +24,12 @@ message RollappMetadata {
...
-  // fee_base_denom is the base denom for fees
-  string fee_base_denom = 11;
-  // native_base_denom is the base denom for the native token
-  string native_base_denom = 12;
+  // fee_denom is the base denom for fees
+  DenomMetadata fee_denom = 11;
+}
+
+message DenomMetadata {
+  string display = 1;
```
Comment (mtsitrin) [inline proto/dymensionxyz/dymension/rollapp/metadata.proto:32]: same as `token_symbol`? why `token_symbol` not here otherwise?

File: proto/dymensionxyz/dymension/rollapp/metadata.proto [hunk 6]
```diff
@@ -24,8 +24,12 @@ message RollappMetadata {
   string token_symbol = 9;
   // explorer_url is the rollapp's block explorer link
   string explorer_url = 10;
-  // fee_base_denom is the base denom for fees
-  string fee_base_denom = 11;
-  // native_base_denom is the base denom for the native token
-  string native_base_denom = 12;
+  // fee_denom is the base denom for fees
+  DenomMetadata fee_denom = 11;
```
Comment (mtsitrin) [inline proto/dymensionxyz/dymension/rollapp/metadata.proto:28]: @omritoptix won't it be the same as the `native_denom`? we need additional struct for `fee_denom`?
IIRC we expect the denoms to be registered in the bank model for UI support

Comment (omritoptix) [reply proto/dymensionxyz/dymension/rollapp/metadata.proto:28]: not necesarily. we may have rollapps which will have gov denom and operate on e.g udsc as fee etc.

**Review by omritoptix — APPROVED** [review]
