### PR TITLE
fix(bridging_fee): adding cacheCtx for charging fees

### LINKED ISSUE #1554: Refactor bridging fee and add wrapped cached context

### PR DESCRIPTION
**Pull request by mtsitrin**
closes #1554 
* refactor charging fee implementation
* charging fees in cacheCtx to allow clean failure

### CODE REVIEW

File: x/bridgingfee/ibc_module.go [hunk 1]
```diff
@@ -85,44 +83,36 @@ func (w *IBCModule) OnRecvPacket(ctx sdk.Context, packet channeltypes.Packet, re
...
-				EventTypeBridgingFee,
-				sdk.NewAttribute(AttributeKeyFee, fee.String()),
-				sdk.NewAttribute(sdk.AttributeKeySender, transfer.Sender),
-				sdk.NewAttribute(transfertypes.AttributeKeyReceiver, transfer.Receiver),
-				sdk.NewAttribute(transfertypes.AttributeKeyDenom, transfer.Denom),
-				sdk.NewAttribute(transfertypes.AttributeKeyAmount, transfer.Amount),
-			),
-		)
+		// We continue as we don't want the fee charge to fail the transfer in any case.
+		w.logger(ctx, packet, "OnRecvPacket").Error("Charge bridging fee from payer.", "receiver", receiver, "err", err)
```
Comment (danwt) [inline x/bridgingfee/ibc_module.go:103]:
```suggestion
		l.Error("Charge bridging fee from payer.", "receiver", receiver, "err", err)
```

**Review by danwt — DISMISSED** [review]

**Review by omritoptix — APPROVED** [review]
