### PR TITLE
fix: fix grace period finalization test

### LINKED ISSUE #649: current tests does not check if state infos are finalized correctly
With the recent modifications of removing finalized state infos from the BlockHeightToFinalizationQueue, there is no test that is checking state infos are finalized correctly

### PR DESCRIPTION
**Pull request by srene**
## Description
----

With the recent modifications of removing finalized state infos from the BlockHeightToFinalizationQueue, no current tests are checking state infos are finalized correctly. In this PR the TestUpdateState is updated to check that the state infos submitted to the hub get finalized accordingly with the specified dispute period

Closes #649

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x]  Targeted PR against the correct branch
- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [x]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/rollapp/keeper/msg_server_update_state_test.go [hunk 1]
```diff
@@ -147,55 +146,31 @@ func (suite *RollappTestSuite) TestUpdateState() {
 		suite.Require().Nil(err)
 
 		// end block
-		responseEndBlock := suite.App.EndBlocker(suite.Ctx, abci.RequestEndBlock{Height: suite.Ctx.BlockHeight()})
+		suite.App.EndBlocker(suite.Ctx, abci.RequestEndBlock{Height: suite.Ctx.BlockHeight()})
+
+		for i := uint64(0); i <= expectedLatestStateInfoIndex.Index; i++ {
```
Comment (omritoptix) [inline x/rollapp/keeper/msg_server_update_state_test.go:151]: calling it `expectedLatest..` an using it as a var all over the code is a bit confusing. Usually expected is used for comparison.

File: x/rollapp/keeper/msg_server_update_state_test.go [hunk 2]
```diff
@@ -147,55 +146,31 @@ func (suite *RollappTestSuite) TestUpdateState() {
...
+			expectedStateInfo, found := suite.App.RollappKeeper.GetStateInfo(suite.Ctx, rollapp.GetRollappId(), i)
```
Comment (omritoptix) [inline x/rollapp/keeper/msg_server_update_state_test.go:152]: same here with the `expected` var name.
also because it's an index which is incremented by 1, is there a reason it shouldn't be found?
If not, I'd add `suite.Require().EqualTrue(found)`

File: x/rollapp/keeper/msg_server_update_state_test.go [hunk 3]
```diff
@@ -147,55 +146,31 @@ func (suite *RollappTestSuite) TestUpdateState() {
...
+			if found {
+				if uint64(suite.Ctx.BlockHeight()) > disputePeriodInBlocks {
```
Comment (omritoptix) [inline x/rollapp/keeper/msg_server_update_state_test.go:154]: the blokHeight AFAIU shouldn't change between loop iteratins. why is not checked before the loop?

File: x/rollapp/keeper/msg_server_update_state_test.go (hunk 1 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_update_state_test.go:151]: changed

File: x/rollapp/keeper/msg_server_update_state_test.go (hunk 2 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_update_state_test.go:152]: found removed

File: x/rollapp/keeper/msg_server_update_state_test.go (hunk 3 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_update_state_test.go:154]: true. moved outside the loop

**Review by omritoptix — APPROVED** [review]
