### PR TITLE
fix(sequencers): incorrect sorting mechanism allows manipulation of proposer selection

### LINKED ISSUE #1291: Incorrect sorting mechanism allows manipulation of proposer selection
We'll enforce **single** denom for the sequencer bond to mitigate this

### PR DESCRIPTION
**Pull request by mtsitrin**
## Description

----

Closes #1291 

This PR does the following:
* better enforcement of single denom for sequencer bond 
* requires `MinBond` param to be > 0 (instead >= 0 currently)

### CODE REVIEW

File: x/sequencer/keeper/msg_server_create_sequencer_test.go [hunk 1]
```diff
@@ -55,45 +49,63 @@ func (suite *SequencerTestSuite) TestMinBond() {
 			bond:          sdk.NewCoin(bond.Denom, bond.Amount.Quo(sdk.NewInt(2))),
 			expectedError: types.ErrInsufficientBond,
 		},
+		{
+			name:          "wrong bond denom",
```
Comment (omritoptix) [inline x/sequencer/keeper/msg_server_create_sequencer_test.go:53]: also this test seems to test the wrong thing - i.e fail on invalid coin denom vs valid but not what we expected (i.e wrong).

**Review by omritoptix — CHANGES_REQUESTED** [review]

File: x/sequencer/keeper/msg_server_create_sequencer.go [hunk 2]
```diff
@@ -63,28 +63,22 @@ func (k msgServer) CreateSequencer(goCtx context.Context, msg *types.MsgCreateSe
...
-		}
-
-		if msg.Bond.Amount.LT(minBond.Amount) {
-			return nil, errorsmod.Wrapf(
-				types.ErrInsufficientBond, "got %s, expected %s", msg.Bond.Amount, minBond,
-			)
-		}
+	// validate bond requirement
+	minBond := k.GetParams(ctx).MinBond
+	if !msg.Bond.IsGTE(minBond) {
```
[the remark this answers is not in the document]
Comment (mtsitrin) [reply x/sequencer/keeper/msg_server_create_sequencer.go:68]: it's checked in `IsGTE`
```
// IsGTE returns true if they are the same type and the receiver is
// an equal or greater value

File: x/sequencer/keeper/msg_server_create_sequencer_test.go (hunk 1 above)
Comment (mtsitrin) [reply x/sequencer/keeper/msg_server_create_sequencer_test.go:51]: changed the test a bit

**Review by omritoptix — APPROVED** [review]
