### PR TITLE
fix(eibc): authorization min fee truncating

### LINKED ISSUE #1733: creation of eibc demand orders upon ackErr and timeout `truncateInt` the fee
This is problematic since our authZ check calculates the min fee a bridge LP is willing to accept without truncateInt. this causes a situation where:

1. bridgeLP set 0.15% as acceptance fee
2. AckErr fee is currently set as 0.15% 
3. AckErr computes min nominal fee which may be  != acceptance fee of bridgeLP (lower in some cases).

e.g `order fee 55418436445222322.000000000000000000 is less than minimum fee 55418436445222322.458500000000000000: unauthorized` 

We should calculate the fee the same (without truncating int)

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #1733 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/eibc/types/fulfill_order_authorization.go [hunk 1]
```diff
@@ -92,13 +92,13 @@ func (a FulfillOrderAuthorization) Accept(
 	}
 
 	// Check if the order fee meets the minimum LP fee percentage
-	orderFeeDec, err := math.LegacyNewDecFromStr(mFulfill.ExpectedFee)
-	if err != nil {
+	orderFeeDec, ok := math.NewIntFromString(mFulfill.ExpectedFee)
```
Comment (mtsitrin) [inline x/eibc/types/fulfill_order_authorization.go:95]:
```suggestion
	orderFee, ok := math.NewIntFromString(mFulfill.ExpectedFee)
```

**Review by mtsitrin — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]

**Review by mtsitrin — APPROVED** [review]
