### PR TITLE
fix(delayedack): fix missing validation of channel id when validating rollapp packet

### LINKED ISSUE #794: add validation for channel id upon rollapp validation on delayed ack
Currently we're only validating the sequencer val hash. 
As reported by Khanh from decentrio, a malicious chain could:
1. fake the rollapp packet id
2. fake the nextValHash to be the same as our sequencer

In that case the malicious rollapp packet can snick into the queue. 

We should also verify the rollapp against the known channel and by that prevent that.

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #794 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/delayedack/keeper/keeper.go [hunk 1]
```diff
@@ -187,19 +187,26 @@ func (k *Keeper) LookupModuleByChannel(ctx sdk.Context, portID, channelID string
...
 	if !found {
-		return errorsmod.Wrapf(rollapptypes.ErrUnknownRollappID, "state info not found for the rollapp: %s with index: %d", rollapp, latestStateIndex.Index)
+		return errorsmod.Wrapf(rollapptypes.ErrUnknownRollappID, "state info not found for the rollappID: %s with index: %d", rollappID, latestStateIndex.Index)
+	}
+	rollapp, found := k.rollappKeeper.GetRollapp(ctx, rollappID)
+	if !found {
+		return errorsmod.Wrapf(rollapptypes.ErrUnknownRollappID, "rollappID not found for the rollappID: %s", rollappID)
+	}
+	// check if the channelID matches the rollappID's channelID
+	if rollapp.ChannelId != channelID {
```
Comment (mtsitrin) [inline x/delayedack/keeper/keeper.go:207]: It means that w/o the genesis event, no ibc transfer will work for this rollapp.
right?

Comment (mtsitrin) [reply x/delayedack/keeper/keeper.go:207]: IMO this check should be done in `ExtractRollappIDAndTransferPacket`
* validates the rollappID before returning it
* no need for additional `k.rollappKeeper.GetRollapp` call

Comment (zale144) [reply x/delayedack/keeper/keeper.go:210]: Works for me

**Review by mtsitrin — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]
