### PR TITLE
fix(rollapp): trigger EventTypeStatusChange instead of EventTypeStateUpdate on state update finalization

### LINKED ISSUE #875: wrong emitted event upon state update finalization
it should emit EventTypeStatusChange event, and not EventTypeStateUpdate

### PR DESCRIPTION
**Pull request by srene**
## Description

----

Closes #875 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

## Summary by CodeRabbit

- **Bug Fixes**
  - Updated event type from `EventTypeStateUpdate` to `EventTypeStatusChange` to ensure correct event handling.

- **Tests**
  - Enhanced `TestFinalize` function to capture and validate events more accurately.
  - Introduced `findEvent` function to streamline event searching in test responses.

### CODE REVIEW

File: x/rollapp/keeper/block_height_to_finalization_queue_test.go [hunk 1]
```diff
@@ -124,3 +127,13 @@ func createNBlockHeightToFinalizationQueue(keeper *keeper.Keeper, ctx sdk.Contex
...
+
+func findEvent(response abci.ResponseEndBlock, eventType string) bool {
+	found := false
+	for _, event := range response.Events {
+		if event.Type == eventType {
+			found = true
+		}
+	}
+	return found
+}
```
Comment (zale144) [inline x/rollapp/keeper/block_height_to_finalization_queue_test.go:139]:
```suggestion
func findEvent(response abci.ResponseEndBlock, eventType string) bool {
	for _, event := range response.Events {
		if event.Type == eventType {
			return true
		}
	}
	return false
}
```

**Review by zale144 — CHANGES_REQUESTED** [review]

File: x/rollapp/keeper/block_height_to_finalization_queue_test.go (hunk 1 above)
Comment (danwt) [reply x/rollapp/keeper/block_height_to_finalization_queue_test.go:139]: slices.ContainsFunc

Comment (srene) [reply x/rollapp/keeper/block_height_to_finalization_queue_test.go]: replaced by slices.ContainsFunc

**Review by danwt — APPROVED** [review]

**Review by mtsitrin — APPROVED** [review]
