### PR TITLE
fix(streamer): don't distribute abstained part of sponsored distribution

### LINKED ISSUE #1095: Change the distribution logic if some part of the sponsored stream is abstained
Let's say we have the following distribution in a sponsorship:

Total: 100
Gauge 1: 30%
Gauge 2: 50%
Abstained: 20%

We want to distribute 100 DYM according to this distribution. Since 20% is abstained, we will normalize the figures for Gauge 1 and Gauge 2.

The total "active" voting power is 80%, which comes from 30% (Gauge 1) + 50% (Gauge 2).

Gauge 1: 30% / 80% = 37.5% (in the new distribution)
Gauge 2: 50% / 80% = 62.5% (in the new distribution)
So, Gauge 1 gets 37.5 DYM, and Gauge 2 gets 62.5 DYM.

This is how it currently works, but it’s not the intended outcome. The goal is to have the abstained portion remain unallocated. For example, if someone with a large amount of staked DYM chooses not to allocate it yet, preferring to wait and decide later, that portion should remain abstained.

All the remaining coins must stay in the x/streamer account and will remain there if any part is left after the stream is terminated. These coins may be used for future purposes.

### PR DESCRIPTION
**Pull request by keruch**
## Description

Don't distribute the abstained part of the sponsored distribution.

----

Closes #1095 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

## Summary by CodeRabbit

- **New Features**
  - Simplified weight calculation in the distribution function for better performance and clarity.
  - Introduced a comprehensive test suite for the `DistrInfoFromDistribution` function to ensure accuracy and reliability.

- **Bug Fixes**
  - Enhanced logic to handle various distribution scenarios, including empty and multi-gauge distributions.

- **Documentation**
  - Updated comments for clarity concerning the new weight calculation process.

### CODE REVIEW

**Review by omritoptix — APPROVED** [review]

File: x/streamer/types/distr_info.go [hunk 1]
```diff
@@ -36,29 +35,19 @@ func (r DistrRecord) ValidateBasic() error {
...
+			Weight:  g.Power,
+		})
 	}
 
 	return &DistrInfo{
-		TotalWeight: totalWeight,
+		TotalWeight: d.VotingPower,
 		Records:     records,
 	}
 }
```
Comment (danwt) [inline x/streamer/types/distr_info.go:53]: This should really be a method!
I asked for this before you ignored it!

Generally the development world accepted OOP as a good thing in most cases. It makes code easier to read, requires less verbose naming, allows better autocomplete, and gives better understanding of package functionality when viewing structural layout of a packge

Comment (danwt) [reply x/streamer/types/distr_info.go:53]: This should be a method .Info()

**Review by danwt — APPROVED** [review]
Curiuos what is the difference between streamer DistrInfo and sponsorship Distribution?
