### PR TITLE
fix (rollapp): allow creating rollapp same eip155 when forking

### LINKED ISSUE #807: Unable to create rollapp using the same EIP155 when forking
It is not possible to create a new rollapp after forking using the same id and only increasing the revision number when using EIP155.

### PR DESCRIPTION
**Pull request by srene**
## Description

This PR is a fix to allow  creating rollapp with the same  EIP155 when forking, but increasing revision number

----

Closes #807 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

**Comment by danwt** [comment]
e2e are failing

File: ibctesting/utils_test.go [hunk 1]
```diff
@@ -75,6 +76,7 @@ func (suite *IBCTestUtilSuite) SetupTest() {
 }
 
 func (suite *IBCTestUtilSuite) CreateRollapp() {
+	fmt.Println(suite.rollappChain.ChainID)
```
Comment (danwt) [inline ibctesting/utils_test.go:79]: del

File: x/rollapp/types/chain_id.go [hunk 2]
```diff
@@ -66,6 +77,22 @@ func getEIP155ID(chainID string) (*big.Int, error) {
...
+	matches := strings.Split(chainID, "-")
+	if len(matches) == 1 {
+		return 0, nil
+	}
+	if len(matches) != 2 {
+		return 0, errorsmod.Wrapf(ErrInvalidRollappID, "unable to parse revision number")
+	}
+	revision, err := strconv.ParseUint(matches[1], 0, 64)
+	if err != nil {
+		return 0, errorsmod.Wrapf(ErrInvalidRollappID, "unable to parse revision number: error: %e", err)
```
Comment (danwt) [inline x/rollapp/types/chain_id.go:91]: %e is wrong, it should be %w or %v I think

**Review by danwt — CHANGES_REQUESTED** [review]

File: ibctesting/utils_test.go (hunk 1 above)
Comment (srene) [reply ibctesting/utils_test.go]: done

File: x/rollapp/types/chain_id.go (hunk 2 above)
Comment (srene) [reply x/rollapp/types/chain_id.go]: rplaced for %v

**Review by danwt — DISMISSED** [review]

File: x/rollapp/keeper/msg_server_create_rollapp.go [hunk 3]
```diff
@@ -26,9 +27,15 @@ func (k msgServer) CreateRollapp(goCtx context.Context, msg *types.MsgCreateRoll
...
-		if _, isFound := k.GetRollappByEIP155(ctx, rollappId.GetEIP155ID()); isFound {
+		rollapp, isFound := k.GetRollappByEIP155(ctx, rollappId.GetEIP155ID())
+		// allow replacing EIP155 only when forking (previous rollapp is frozen)
+		if isFound && !rollapp.Frozen {
 			return nil, types.ErrRollappExists
 		}
+		previousRollappChainId, _ := types.NewChainID(rollapp.RollappId)
+		if isFound && rollappId.GetRevisionNumber() != previousRollappChainId.GetRevisionNumber()+1 {
+			return nil, errorsmod.Wrapf(types.ErrInvalidRollappID, "revision number should be %d", previousRollappChainId.GetRevisionNumber()+1)
+		}
```
Comment (zale144) [inline x/rollapp/keeper/msg_server_create_rollapp.go:38]: Why not move the `rollappId` checks to a separate method

```suggestion
func (k msgServer) checkIfRollappExists(msg *types.MsgCreateRollapp, ctx sdk.Context) error {
	rollappId, err := types.NewChainID(msg.RollappId)
	if err != nil {
		return err
	}
	// check to see if the RollappId has been registered before
	if _, isFound := k.GetRollapp(ctx, rollappId.GetChainID()); isFound {
		return types.ErrRollappExists
	}

	if !rollappId.IsEIP155() {
		return nil
	}

	// check to see if the RollappId has been registered before with same key
	rollapp, isFound := k.GetRollappByEIP155(ctx, rollappId.GetEIP155ID())
	// allow replacing EIP155 only when forking (previous rollapp is frozen)
	if !isFound {
		return nil
	}

	if !rollapp.Frozen {
		return types.ErrRollappExists
	}

	previousRollappChainId, _ := types.NewChainID(rollapp.RollappId)
	nextRevisionNumber := previousRollappChainId.GetRevisionNumber() + 1

	if rollappId.GetRevisionNumber() != nextRevisionNumber {
		return errorsmod.Wrapf(types.ErrInvalidRollappID, "revision number should be %d", nextRevisionNumber)
	}
	return nil
}

```

File: x/rollapp/types/chain_id.go [hunk 4]
```diff
@@ -43,20 +46,28 @@ func NewChainID(id string) (ChainID, error) {
 	if err != nil {
 		return ChainID{}, err
 	}
+	revision, err := getRevisionNumber(chainID)
+	if err != nil {
+		return ChainID{}, err
+	}
+	matches := strings.Split(chainID, "-")
```
Comment (zale144) [inline x/rollapp/types/chain_id.go:53]: if we add this test case:

```
{
	name:      "starts with dash",
	rollappId: "-1234",
	eip:       false,
	valid:     false,
}
```

to the `TestCreateRollappId` test, the resulting `ChainID` will be:

```
ChainID {
	chainID: "-1234",
	eip155ID: nil,
	revision: 1234,
	name:     "",
}
```

**Review by zale144 — CHANGES_REQUESTED** [review]

File: x/rollapp/types/chain_id.go (hunk 4 above)
Comment (zale144) [reply x/rollapp/types/chain_id.go:53]: And yeah, the test will fail, an error will be expected, but there won't be any

File: x/rollapp/keeper/msg_server_create_rollapp.go (hunk 3 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_create_rollapp.go]: func added

File: x/rollapp/types/chain_id.go (hunk 4 above)
Comment (srene) [reply x/rollapp/types/chain_id.go:53]: empty name fix added

File: x/rollapp/keeper/msg_server_create_rollapp.go [hunk 5]
```diff
@@ -49,3 +38,32 @@ func (k msgServer) CreateRollapp(goCtx context.Context, msg *types.MsgCreateRoll
...
+	}
+	// check to see if the RollappId has been registered before
+	if _, isFound := k.GetRollapp(ctx, rollappId.GetChainID()); isFound {
+		return types.ErrRollappExists
+	}
+	if !rollappId.IsEIP155() {
+		return nil
+	}
+	// check to see if the RollappId has been registered before with same key
+	rollapp, isFound := k.GetRollappByEIP155(ctx, rollappId.GetEIP155ID())
```
Comment (mtsitrin) [inline x/rollapp/keeper/msg_server_create_rollapp.go:55]: would rename `rollapp` to `existingRollapp` for clarity

File: x/rollapp/keeper/msg_server_create_rollapp.go [hunk 6]
```diff
@@ -49,3 +38,32 @@ func (k msgServer) CreateRollapp(goCtx context.Context, msg *types.MsgCreateRoll
...
+	// allow replacing EIP155 only when forking (previous rollapp is frozen)
+	if !isFound {
+		return nil
+	}
+	if !rollapp.Frozen {
+		return types.ErrRollappExists
+	}
+	previousRollappChainId, _ := types.NewChainID(rollapp.RollappId)
+	nextRevisionNumber := previousRollappChainId.GetRevisionNumber() + 1
+	if rollappId.GetRevisionNumber() != nextRevisionNumber {
```
Comment (mtsitrin) [inline x/rollapp/keeper/msg_server_create_rollapp.go:65]: we probably should enforce the same chain name
to avoid `rollappX_100-1` forking into `rollappY_100-2`

File: x/rollapp/keeper/msg_server_create_rollapp.go (hunk 5 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_create_rollapp.go]: renamed

File: x/rollapp/keeper/msg_server_create_rollapp.go (hunk 6 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_create_rollapp.go:70]: added name check

**Review by omritoptix — APPROVED** [review]
