### PR TITLE
fix: limit the number of permissioned addresses introduced in a MsgCreateRollapp

### LINKED ISSUE #691: Attackers can submit large amounts of permissioned addresses to crash nodes

### PR DESCRIPTION
**Pull request by srene**
## Description

This PR adds a check for the number of permissioned addresses introduced for a "create rollapp" tx.
It alllows up to max number of sequencers number of permissioned addresses.
It also limits the max number of sequencers to 100
max sequencers set to 0,  or not set, is for permissionless rollapps since it does not allow to add permissioned addresses.
for permissioned rollapps it requires to set max sequencer number
----

Closes #691 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/rollapp/types/message_create_rollapp.go [hunk 1]
```diff
@@ -48,10 +50,13 @@ func (msg *MsgCreateRollapp) ValidateBasic() error {
...
-	if msg.GetMaxSequencers() == 0 {
-		return sdkerrors.Wrap(ErrInvalidMaxSequencers, "max-sequencers must be greater than 0")
-	}
 
+	if msg.GetMaxSequencers() > MaxAllowedSequencers {
+		return sdkerrors.Wrapf(ErrInvalidMaxSequencers, "is not possible to create rollapps with more than %d sequencers", MaxAllowedSequencers)
+	}
+	if uint64(len(msg.PermissionedAddresses)) > msg.GetMaxSequencers() {
+		return sdkerrors.Wrapf(ErrTooManyPermissionedAddresses, "invalid number of permissioned addresses (%d) for %d max sequencers", len(msg.PermissionedAddresses), msg.GetMaxSequencers())
+	}
```
Comment (danwt) [inline x/rollapp/types/message_create_rollapp.go:59]: Maybe it's known already, but apparently `	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"` is deprecated and we should use `//	cosmossdk.io/errors` instead

Comment (danwt) [reply x/rollapp/types/message_create_rollapp.go:59]:
```suggestion
		return sdkerrors.Wrapf(ErrInvalidMaxSequencers, "is not possible to create rollapps with more than %d sequencers", MaxAllowedSequencers)
	}
	if uint64(len(msg.PermissionedAddresses)) > msg.GetMaxSequencers() {
		return sdkerrors.Wrapf(ErrTooManyPermissionedAddresses, "invalid number of permissioned addresses for max sequencers: n permissioned: %d: max: %d", len(msg.PermissionedAddresses), msg.GetMaxSequencers())
	}
```

Comment (danwt) [reply x/rollapp/types/message_create_rollapp.go:59]: prefer making the error strings a bit more structured rather than inlining variables
it makes it easier to ctrl-f

**Review by danwt — DISMISSED** [review]
Approved but have a question about the error wrapping and the error string formatting

File: x/rollapp/client/cli/tx_create_rollapp.go [hunk 2]
```diff
@@ -66,7 +66,9 @@ func CmdCreateRollapp() *cobra.Command {
 				metadatas,
 				genesisAccounts,
 			)
-
+			if err := msg.ValidateBasic(); err != nil {
```
Comment (omritoptix) [inline x/rollapp/client/cli/tx_create_rollapp.go:69]: I believe this is already done automatically as part of the `GenerateOrBroadcastTxCLI` so no need to call it.

File: x/rollapp/types/message_create_rollapp.go [hunk 3]
```diff
@@ -9,6 +9,8 @@ const TypeMsgCreateRollapp = "create_rollapp"
 
 var _ sdk.Msg = &MsgCreateRollapp{}
 
+const MaxAllowedSequencers = 100
```
Comment (omritoptix) [inline x/rollapp/types/message_create_rollapp.go:12]: create an issue please to make it a param

Comment (srene) [reply x/rollapp/types/message_create_rollapp.go:12]: done

File: x/rollapp/types/message_create_rollapp.go (hunk 1 above)
Comment (srene) [reply x/rollapp/types/message_create_rollapp.go:59]: error msgs updated

**Review by omritoptix — DISMISSED** [review]

**Comment by omritoptix** [comment]
@srene build fails

**Review by omritoptix — APPROVED** [review]

File: x/rollapp/types/message_create_rollapp.go [hunk 4]
```diff
@@ -46,12 +48,15 @@ func (msg *MsgCreateRollapp) GetSignBytes() []byte {
 func (msg *MsgCreateRollapp) ValidateBasic() error {
 	_, err := sdk.AccAddressFromBech32(msg.Creator)
 	if err != nil {
-		return sdkerrors.Wrapf(sdkerrors.ErrInvalidAddress, "invalid creator address (%s)", err)
-	}
-	if msg.GetMaxSequencers() == 0 {
```
Comment (mtsitrin) [inline x/rollapp/types/message_create_rollapp.go:51]: why remove this check?
currently `maxSequencer = 0` makes it impossible to register sequencers.

if we want it to be limitless, we need to change sequencer logic as well

Comment (srene) [reply x/rollapp/types/message_create_rollapp.go:51]: i updated  sequencer logic to skip num sequencers check when maxSequencer is 0

Comment (danwt) [reply x/rollapp/types/message_create_rollapp.go:51]: I wonder if we want some optional type or *int instead of overloading 0?
(Not just here but in general)
I don't really have a strong opinion, I think overloading can be fine too

**Review by mtsitrin — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]
