### PR TITLE
fix(delayedack): handle finalization errors per rollapp

### LINKED ISSUE #670: Finalization queue logic should be done per rollapp
Currently if one rollapp finalization fail we fail the entire rollapps finalization.
We should fail it on a per rollapp basis.

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #670 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 1]
```diff
@@ -2,62 +2,81 @@ package keeper
...
+		}
+		// remove the blockHeightToFinalizationQueue if all the rollapps are finalized
+		if len(rollappsToRemoveFromQueue) == len(blockHeightToFinalizationQueue.FinalizationQueue) {
+			k.RemoveBlockHeightToFinalizationQueue(ctx, blockHeightToFinalizationQueue.CreationHeight)
+		} else {
+			// remove only the rollapps that were successfully finalized
+			blockHeightToFinalizationQueue.FinalizationQueue = slices.DeleteFunc(blockHeightToFinalizationQueue.FinalizationQueue,
+				func(si types.StateInfoIndex) bool {
+					return slices.Contains(rollappsToRemoveFromQueue, si.RollappId)
+				})
```
Comment (danwt) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:51]: this is an n^2 algorithm right
I think it's fine now because we don't have many rollapps
but IMO you need to add a warning/todo here to fix it

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 2]
```diff
@@ -2,62 +2,81 @@ package keeper
...
-			keeperHooks := k.GetHooks()
-			err := keeperHooks.AfterStateFinalized(ctx, stateInfoIndex.RollappId, &stateInfo)
+			err := osmoutils.ApplyFuncIfNoError(ctx,
+				func(ctx sdk.Context) error {
+					return k.finalizePendingState(ctx, stateInfoIndex)
+				})
 			if err != nil {
-				return fmt.Errorf("after state finalized: %w", err)
+				k.Logger(ctx).Error("failed to finalize state", "rollapp", stateInfoIndex.RollappId, "index", stateInfoIndex.Index, "error", err.Error())
+				continue
```
Comment (danwt) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:39]: Can you add a comment, either here, or maybe as the function docstring, which explains the high level philosophy here about how errors are handled? Like the full lifecycle.

For example, what happens if the rollapp doesnt finalize over and over?
Needs some explanation and guidance, otherwise I'm reading the code and it just seems super error prone and I'm not sure what the assumptions and guarantees are

Comment (danwt) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:39]: Basically, like, even though the code may be correct, it's not obvious that it is. There is some product assumption here

File: x/rollapp/keeper/block_height_to_finalization_queue_test.go [hunk 3]
```diff
@@ -129,6 +304,16 @@ func createNBlockHeightToFinalizationQueue(keeper *keeper.Keeper, ctx sdk.Contex
...
 
+func countFinalized(response abci.ResponseEndBlock) int {
+	count := 0
+	for _, event := range response.Events {
+		if event.Type == types.EventTypeStatusChange {
+			count++
+		}
+	}
+	return count
+}
```
Comment (danwt) [inline x/rollapp/keeper/block_height_to_finalization_queue_test.go:315]: could also use len(slices.DeleteFunc(..))

**Review by danwt — CHANGES_REQUESTED** [review]
Looks correct to me but I think it could do with some better documentation as this is a very critical part of the code

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 4]
```diff
@@ -2,62 +2,84 @@ package keeper
...
+			err := osmoutils.ApplyFuncIfNoError(ctx,
+				func(ctx sdk.Context) error {
+					return k.finalizePendingState(ctx, stateInfoIndex)
+				})
 			if err != nil {
-				return fmt.Errorf("after state finalized: %w", err)
+				// if a rollapp's state fails to finalize, move on (state index will stay in the queue)
+				// TODO: think about (non)recoverable errors and how to handle them accordingly
+				k.Logger(ctx).Error("failed to finalize state", "rollapp", stateInfoIndex.RollappId, "index", stateInfoIndex.Index, "error", err.Error())
+				continue
```
Comment (mtsitrin) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:42]: can it cause invariant break?
if some states of a rollapp are finalized but some don't

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 5]
```diff
@@ -2,62 +2,84 @@ package keeper
...
 			}
-
-			// emit event
-			ctx.EventManager().EmitEvent(
-				sdk.NewEvent(types.EventTypeStatusChange,
-					stateInfo.GetEvents()...,
-				),
-			)
+			rollappsToRemoveFromQueue = append(rollappsToRemoveFromQueue, stateInfoIndex.RollappId)
```
Comment (mtsitrin) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:44]: u assume single state per rollapp in the queue?

File: x/rollapp/keeper/keeper.go [hunk 6]
```diff
@@ -21,22 +21,36 @@ type Keeper struct {
 
 	ibcClientKeeper types.IBCClientKeeper
 	channelKeeper   types.ChannelKeeper
+
+	finalizePending func(ctx sdk.Context, stateInfoIndex types.StateInfoIndex) error
```
Comment (mtsitrin) [inline x/rollapp/keeper/keeper.go:25]: why we need this as an interface?

**Review by mtsitrin — APPROVED** [review]

File: x/rollapp/keeper/keeper.go (hunk 6 above)
Comment (zale144) [reply x/rollapp/keeper/keeper.go:25]: To be able to mock it easily, for returning errors on certain rollapp state indexes in tests

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 7]
```diff
@@ -2,65 +2,114 @@ package keeper
...
+	})
+	if err != nil {
+		// TODO: think about (non)recoverable errors and how to handle them accordingly
+		k.Logger(ctx).Error(
+			"failed to finalize state",
+			"rollapp", stateInfoIndex.RollappId,
+			"index", stateInfoIndex.Index,
+			"error", err.Error(),
+		)
+		return fmt.Errorf("finalize state: %w", err)
```
Comment (danwt) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:65]: you shouldn't really log and return an error, generally

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 8]
```diff
@@ -2,65 +2,114 @@ package keeper
...
+}
+
+func (k Keeper) updateQueueForHeight(ctx sdk.Context, blockHeightToFinalizationQueue types.BlockHeightToFinalizationQueue, failedRollapps map[string]uint64) {
+	// remove the blockHeightToFinalizationQueue if all the rollapps' states are finalized
+	if len(failedRollapps) == 0 {
+		k.RemoveBlockHeightToFinalizationQueue(ctx, blockHeightToFinalizationQueue.CreationHeight)
+		return
+	}
+	// remove from the queue only the rollapps that were successfully finalized at all indices.
+	// for failed rollapps at current height, all state indices including and following the failed index will stay in the queue
```
Comment (danwt) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:103]:
```suggestion
	// remove from the queue the rollapps that were successfully finalized at all indices.
	// for failed rollapps at current height, all state indices including and following the failed index will stay in the queue
```

**Review by danwt — CHANGES_REQUESTED** [review]

File: x/rollapp/keeper/block_height_to_finalization_queue.go (hunk 8 above)
Comment (zale144) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:103]: Is this really a blocker?

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 9]
```diff
@@ -2,65 +2,114 @@ package keeper
...
-					stateInfo.GetEvents()...,
-				),
-			)
+		k.finalizeQueueForHeight(ctx, blockHeightToFinalizationQueue, failedRollapps)
+	}
+}
+
+func (k Keeper) finalizeQueueForHeight(ctx sdk.Context, queue types.BlockHeightToFinalizationQueue, failedRollapps map[string]uint64) {
+	// finalize pending states
+	for _, stateInfoIndex := range queue.FinalizationQueue {
```
[the remark this answers is not in the document]
Comment (zale144) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:38]: the iteration is the same as it was, the queue is retrieved the same way as previously

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 10]
```diff
@@ -2,65 +2,114 @@ package keeper
...
+	if len(failedRollapps) == 0 {
+		k.RemoveBlockHeightToFinalizationQueue(ctx, blockHeightToFinalizationQueue.CreationHeight)
+		return
+	}
+	// remove from the queue only the rollapps that were successfully finalized at all indices.
+	// for failed rollapps at current height, all state indices including and following the failed index will stay in the queue
+	blockHeightToFinalizationQueue.FinalizationQueue = slices.DeleteFunc(blockHeightToFinalizationQueue.FinalizationQueue,
+		func(si types.StateInfoIndex) bool {
+			idx, failed := failedRollapps[si.RollappId]
+			return !failed || si.Index < idx
```
[the remark this answers is not in the document]
Comment (zale144) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:107]: it means, while iterating the queue for deleting the successfully finalized states, we remove them if
- it was not found in the `failedRollapps` map
- if it was found, the indexes to be deleted should only be the ones up to the point of the index of the first failed state change

File: x/rollapp/keeper/block_height_to_finalization_queue.go [hunk 11]
```diff
@@ -2,65 +2,114 @@ package keeper
...
-				return fmt.Errorf("after state finalized: %w", err)
-			}
-
-			// emit event
-			ctx.EventManager().EmitEvent(
-				sdk.NewEvent(types.EventTypeStatusChange,
-					stateInfo.GetEvents()...,
-				),
-			)
+		k.finalizeQueueForHeight(ctx, blockHeightToFinalizationQueue, failedRollapps)
```
Comment (omritoptix) [inline x/rollapp/keeper/block_height_to_finalization_queue.go:32]: seems to me like the you can have a state index of e.g rollapp abc being finalized after  previous state index of rollapp abc failed in previous queue. e.g :

1. queue1 = Queue{height: 10, stateIndexes: [{index:1, rollapp: abc}]}
2. queue2 = Queue{height: 11, stateIndexes: [{index:2, rollapp: abc}]} 

In that case, if e.g queue1 fails, it will not finalize the state index, but it seems like queue2 can be independently finalized (As we're trying to finalize each rollapp state index queue without consideration of previous rollapp queue results) vs failing all subsequent state index for that rollapp in the following queues.

_not sure if there is some other place in the code which will fail index2, due to index1 not being finalized, but I don't see it explicitly in this code._

Also I'd suggest a simple validation of only finalizing a state index, if the previous is also finalized (which can avoid all this cases) as currently the finalize function is the following:

```
func (s *StateInfo) Finalize() {
	s.Status = common.Status_FINALIZED
}
```

File: x/rollapp/keeper/block_height_to_finalization_queue.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (omritoptix) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:38]: ok. still not sure what's the answer though.

File: x/rollapp/keeper/block_height_to_finalization_queue.go (hunk 11 above)
Comment (zale144) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:32]: [here ](https://github.com/dymensionxyz/dymension/blob/b159bbd3c001b297f5b8f7d5ba6bc02f8cb308be/x/rollapp/keeper/block_height_to_finalization_queue.go#L39) you can see that if the rollapp had previously failed, its state finalization will be skipped

[here](https://github.com/dymensionxyz/dymension/blob/b159bbd3c001b297f5b8f7d5ba6bc02f8cb308be/x/rollapp/keeper/block_height_to_finalization_queue.go#L46) the failure is recorded and will be kept for the duration of the current `EndBlocker` execution. 

this will result in the failed state changes to not be deleted from the queue and iterated over next iteration of `EndBlocker`.

File: x/rollapp/keeper/block_height_to_finalization_queue.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (omritoptix) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:107]: > if it was found, the indexes to be deleted should only be the ones up to the point of the index of the first failed state change

Ok. I think it should probably be clearer in the func description as it wasn't that clear for me:
```
for failed rollapps at current height, all state indices including and following the failed index will stay in the queue
```

also in the description of the `failedRollapps` is missing with this detail:

```
// cache the rollapps that failed to finalize at current EndBlocker execution
	failedRollapps := make(map[string]uint64)
```

In general lets try to be a bit more explicit.

File: x/rollapp/keeper/block_height_to_finalization_queue.go (hunk 11 above)
Comment (omritoptix) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:32]: right. missed that. my bad.

File: x/rollapp/keeper/block_height_to_finalization_queue.go (hunk 8 above)
Comment (danwt) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:103]: I mean it's wrong and makes it harder to understand tbh

Comment (danwt) [reply x/rollapp/keeper/block_height_to_finalization_queue.go:103]: you can see it confused omri as well
https://github.com/dymensionxyz/dymension/pull/966#discussion_r1680629576

**Review by omritoptix — DISMISSED** [review]

**Review by mtsitrin — DISMISSED** [review]

**Review by danwt — APPROVED** [review]
great work

**Review by mtsitrin — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]
