### PR TITLE
fix(rollapp): EIP155 rollapp keys can be overwritten

### LINKED ISSUE #717: EIP155 keys owned by other rollapps can be overwritten
the ParseChainID function trims whitespace characters from the chain ID before checking whether the chain ID is EVM-compatible. This is problematic because malicious rollapp creators can overwrite the EIP155 key storage into their own rollapps using the same chain ID with extra whitespaces.

### PR DESCRIPTION
**Pull request by srene**
## Description

the ParseChainID function trims whitespace characters from the chain ID before checking whether the chain ID is EVM-compatible. This is problematic because malicious rollapp creators can overwrite the EIP155 key storage into their own rollapps using the same chain ID with extra whitespaces. Using chain ID with extra space will pass the existing rollapp  checks, but it will lead to the same EIP155 key after parsing the chain id.

This PR is aimed at solving this by checking there is no existing rollapp with the same EIP155 key instead of checking by rollapp name.

This PR also refactors how the chain ID is parsed and checked, creating a common struct for that, with the chain id and the eip155 id in case is an EVM compatible id.

Closes #717 

----

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

**Review by danwt — COMMENTED** [review]
I think you're code is correct but the whole thing with the chain id isn't really dealt with cleanly and will probably become quite annoying in the future.

I think we need a function

getValidChainID(string) (string,error) 

which can use

func ParseChainID(chainID string) (*big.Int, error)
https://github.com/dymensionxyz/dymension/blob/4ee6b752dae868b760cb85e2f2533a261038a3ef/x/rollapp/types/chain_id.go#L35-L60
which should be renamed to ParseEVMChainID

and we need to delete the dead code here

https://github.com/dymensionxyz/dymension/blob/4ee6b752dae868b760cb85e2f2533a261038a3ef/x/rollapp/types/chain_id.go#L26-L33

Then we need to use the validated string here
https://github.com/dymensionxyz/dymension/blob/0cebdd327c68620cb09725370130ea582a12dacd/x/rollapp/keeper/msg_server_create_rollapp.go#L52
 instead of using msg.RollappId

**Comment by srene** [comment]
code refactored with a new struct that parses and validates  chain id, and creates an eip155 key in case it is evm compatible. this new code blocks the ability to overwrite the eip155 keys with rollappids with extra whitespace, as stated in the audit.

**Review by mtsitrin — CHANGES_REQUESTED** [review]
This PR does'nt fix the issue. the whitespace is not the issue here.

```
	rollappId := "rollapp_1234-1" 
	badrollappId := "dummy_1234-1" 
```

will overwrite the `1234` eip key with the 2nd rollapp

**Comment by srene** [comment]
> This PR does'nt fix the issue. the whitespace is not the issue here.
> 
> ```
> 	rollappId := "rollapp_1234-1" 
> 	badrollappId := "dummy_1234-1" 
> ```
> 
> will overwrite the `1234` eip key with the 2nd rollapp

True. it appears there was more than one way to overwrite the key, and not only the one described in the audit. should be fixed now. thanks

File: x/rollapp/types/chain_id.go [hunk 1]
```diff
@@ -23,28 +23,35 @@ var (
...
+	chainID := strings.TrimSpace(id)
 
 	if chainID == "" {
-		return nil, errorsmod.Wrapf(ErrInvalidRollappID, "chain-id cannot be empty")
+		return ChainID{}, errorsmod.Wrapf(ErrInvalidRollappID, "chain-id cannot be empty")
 	}
 
 	if len(chainID) > 48 {
-		return nil, errorsmod.Wrapf(ErrInvalidRollappID, "rollapp-id '%s' cannot exceed 48 chars", chainID)
+		return ChainID{}, errorsmod.Wrapf(ErrInvalidRollappID, "rollapp-id '%s' cannot exceed 48 chars", chainID)
```
Comment (danwt) [inline x/rollapp/types/chain_id.go:39]:
```suggestion
				return ChainID{}, errorsmod.Wrapf(ErrInvalidRollappID, "exceeds 48 chars: %s: len: %d", chainID, len(chainID))
```

File: x/rollapp/types/chain_id.go [hunk 2]
```diff
@@ -23,28 +23,35 @@ var (
...
-// ParseChainID parses a string chain identifier's epoch to an Ethereum-compatible
-// chain-id in *big.Int format. The function returns an error if the chain-id has an invalid format
-func ParseChainID(chainID string) (*big.Int, error) {
-	chainID = strings.TrimSpace(chainID)
+func NewChainID(id string) (ChainID, error) {
+	chainID := strings.TrimSpace(id)
 
 	if chainID == "" {
-		return nil, errorsmod.Wrapf(ErrInvalidRollappID, "chain-id cannot be empty")
+		return ChainID{}, errorsmod.Wrapf(ErrInvalidRollappID, "chain-id cannot be empty")
```
Comment (danwt) [inline x/rollapp/types/chain_id.go:35]:
```suggestion
		return ChainID{}, errorsmod.Wrapf(ErrInvalidRollappID, "empty")
```

File: x/rollapp/types/chain_id.go [hunk 3]
```diff
@@ -23,28 +23,35 @@ var (
...
-func IsValidChainID(chainID string) bool {
-	if len(chainID) > 48 {
-		return false
-	}
-
-	return ethermintChainID.MatchString(chainID)
+type ChainID struct {
+	ChainID  string
+	EIP155ID *big.Int
 }
```
Comment (danwt) [inline x/rollapp/types/chain_id.go:29]: can we add a method to get the eip155id as uint64, rather than doing the conversion manually in loads of places

File: x/rollapp/keeper/msg_server_create_rollapp_test.go [hunk 4]
```diff
@@ -117,3 +150,77 @@ func (suite *RollappTestSuite) TestCreateRollappWhenDisabled() {
...
+	badrollapp := types.MsgCreateRollapp{
+		Creator:               alice,
+		RollappId:             badrollappId,
+		MaxSequencers:         1,
+		PermissionedAddresses: []string{},
+	}
+	_, err = suite.msgServer.CreateRollapp(goCtx, &badrollapp)
+	// it should not be possible to register rollapp name with same EIP155 Key
+	suite.Require().ErrorIs(err, types.ErrRollappExists)
+}
```
Comment (danwt) [inline x/rollapp/keeper/msg_server_create_rollapp_test.go:226]: this is a huge duplication, can we have a table test

or use t.Run()

File: x/rollapp/keeper/msg_server_create_rollapp_test.go [hunk 5]
```diff
@@ -107,6 +108,38 @@ func (suite *RollappTestSuite) TestCreateRollappAlreadyExists() {
...
+	// rollapp is the rollapp to create
+	rollapp := types.MsgCreateRollapp{
+		Creator:               alice,
+		RollappId:             rollappName,
+		MaxSequencers:         1,
+		PermissionedAddresses: []string{},
+	}
+	_, err := suite.msgServer.CreateRollapp(goCtx, &rollapp)
+	suite.Require().ErrorIs(err, types.ErrInvalidRollappID)
+}
```
Comment (danwt) [inline x/rollapp/keeper/msg_server_create_rollapp_test.go:141]: table test or use t.Run() subtests

**Review by danwt — CHANGES_REQUESTED** [review]
The struct is a good idea

Can we additionally document the GetRollapp function to better explain what exactly is a rollappId, and why there are two different keys?

https://github.com/dymensionxyz/dymension/blob/a8780eb3915b7a28c75320f8f5a7e0c516ab5cd9/x/rollapp/keeper/rollapp.go#L47-L63

File: x/rollapp/types/chain_id.go (hunk 3 above)
Comment (srene) [reply x/rollapp/types/chain_id.go]: done

File: x/rollapp/keeper/msg_server_create_rollapp_test.go (hunk 4 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_create_rollapp_test.go]: done

File: x/rollapp/keeper/msg_server_create_rollapp_test.go (hunk 5 above)
Comment (srene) [reply x/rollapp/keeper/msg_server_create_rollapp_test.go]: done

**Comment by srene** [comment]
> The struct is a good idea
> 
> Can we additionally document the GetRollapp function to better explain what exactly is a rollappId, and why there are two different keys?
> 
> https://github.com/dymensionxyz/dymension/blob/a8780eb3915b7a28c75320f8f5a7e0c516ab5cd9/x/rollapp/keeper/rollapp.go#L47-L63

comments were added in the function

File: x/rollapp/keeper/msg_server_create_rollapp.go [hunk 6]
```diff
@@ -14,11 +14,27 @@ func (k msgServer) CreateRollapp(goCtx context.Context, msg *types.MsgCreateRoll
 		return nil, types.ErrRollappsDisabled
 	}
 
+	if err := msg.ValidateBasic(); err != nil {
```
Comment (mtsitrin) [inline x/rollapp/keeper/msg_server_create_rollapp.go:17]: this redundent as the `msg.ValidateBasic()` already called by the SDK before getting into this function

Comment (srene) [reply x/rollapp/keeper/msg_server_create_rollapp.go]: fixed

**Review by mtsitrin — APPROVED** [review]
