### PR TITLE
fix(eibc,delaydack): add validation to eibc and delayedack genesis state

### LINKED ISSUE #942: Missing genesis validation
in x/eibc/types/genesis.go:16-18, the Validate method of the GenesisState for the eibc module performs validation checks on the provided genesis.
However, the DemandOrders slice, which could be present in the genesis, is not checked to ensure it contains valid items nor is it deduplicated.
Additionally, the Params are not validated as the Validate method of the Params always returns nil.
Similarly, in x/delayedack/types/genesis.go:20-22, the Validate method of the GenesisState for the delayedack module performs validation checks on the provided genesis.
However, the RollappPackets is not validated to ensure that its items are valid and that there are no duplicates.

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #942 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

File: x/delayedack/types/genesis.go [hunk 1]
```diff
@@ -13,5 +10,15 @@ func DefaultGenesis() *GenesisState {
 // Validate performs basic genesis state validation returning an error upon any
 // failure.
 func (gs GenesisState) Validate() error {
+	rollappPacketMap := make(map[string]struct{})
+	for _, rollappPacket := range gs.GetRollappPackets() {
+		if err := rollappPacket.ValidateBasic(); err != nil {
+			return err
+		}
+		if _, ok := rollappPacketMap[rollappPacket.RollappId]; ok {
```
Comment (mtsitrin) [inline x/delayedack/types/genesis.go:18]: checking dup by `rollappPacket.RollappId`? guess it's wrong

**Review by mtsitrin — CHANGES_REQUESTED** [review]
