### PR TITLE
fix(sequencer): remove `rollapp_id` from `MsgUpdateSequencerInformation`

### LINKED ISSUE #1108: `rollapp_id` field is redundant in `MsgUpdateSequencerInformation` as sequencer address is unique across the chain

### PR DESCRIPTION
**Pull request by zale144**
## Description

----

Closes #1108 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

**Review by mtsitrin — APPROVED** [review]

**Comment by mtsitrin** [comment]
@zale144 linter

File: x/sequencer/keeper/msg_server_update_sequencer.go [hunk 1]
```diff
@@ -4,36 +4,35 @@ import (
...
+	rollapp, found := k.rollappKeeper.GetRollapp(ctx, sequencer.RollappId)
+	if !found {
+		return nil, types.ErrUnknownRollappID
 	}
 
-	sequencer, found := k.GetSequencer(ctx, msg.Creator)
-	if !found {
-		return nil, types.ErrUnknownSequencer
+	if rollapp.Frozen {
+		return nil, types.ErrRollappJailed
```
Comment (omritoptix) [inline x/sequencer/keeper/msg_server_update_sequencer.go:31]: `ErrRollappJailed` is prob a weird name for a frozen rollapp

File: x/sequencer/keeper/msg_server_update_sequencer.go [hunk 2]
```diff
@@ -4,36 +4,35 @@ import (
...
 
-	if rollapp.Frozen {
-		return nil, types.ErrRollappJailed
+	if sequencer.Jailed {
+		return nil, types.ErrSequencerJailed
 	}
 
-	if err := msg.VMSpecificValidate(rollapp.VmType); err != nil {
-		return nil, errorsmod.Wrapf(types.ErrInvalidRequest, err.Error())
+	rollapp, found := k.rollappKeeper.GetRollapp(ctx, sequencer.RollappId)
```
Comment (omritoptix) [inline x/sequencer/keeper/msg_server_update_sequencer.go:25]: shouldnt it be MustGetRollapp? thinking if there is any situation where the sequencer has a rollapp id set and this rollapp doesn't exist. I think it's a broken invariant in that case.

**Review by omritoptix — DISMISSED** [review]

**Review by mtsitrin — APPROVED** [review]
