### PR TITLE
fix(denommetada): sync validations between different token metadata components

### LINKED ISSUE #750: sync validations between different `token metadata` componentts
currently we have a few places that use the token metadata:
1. `x/denommetadata`
2. `vfc`
3. `x/rollapp` on rollapp registration

the validation scheme should be the same, as they all need to pass for successful registration.
--------
e.g this case, passes the `rollapp creation` but fails on `vfc` registration

```
[
    {
        "description": "rollapp rollappevm_1234-1 native token",
        "base": "urax",
        "denom_units": [
            {
                "denom": "urax",
                "exponent": 0
            }
        ],
        "name": "rollappevm_1234-1 urax",
        "symbol": "URAX",
        "display": "urax"
    }
]
```

### PR DESCRIPTION
**Pull request by hoangdv2429**
## Description

Closes #750

This pr add validation for denommetadata and rollapp as vfc validation is correct.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x]  Targeted PR against the correct branch
- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x]  Linked to the GitHub issue with discussion and accepted design
- [x]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

**Review by omritoptix — APPROVED** [review]

**Comment by omritoptix** [comment]
@hoangdv2429 can we add tests to verify it fails on the suggested case?

**Comment by hoangdv2429** [comment]
> @hoangdv2429 can we add tests to verify it fails on the suggested case? 

I'll add it tmr if we don't have higher priority task 🤞

File: x/rollapp/keeper/keeper.go [hunk 1]
```diff
@@ -124,6 +124,11 @@ func (k Keeper) registerDenomMetadata(ctx sdk.Context, rollapp types.Rollapp) er
 			metadata.DenomUnits[j] = &newDu
 		}
 
+		// validate metadata
+		if validity := metadata.Validate(); validity != nil {
```
Comment (mtsitrin) [inline x/rollapp/keeper/keeper.go:128]: @hoangdv2429 it's too late to detect the malformed metadata.
This should be validated on rollapp creation as well
